name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build (AArch64)
      run: |
        CXX=aarch64-linux-android33-clang++ ./build.sh
        zip -r ih8sn-aarch64.zip META-INF system push.ps1 push.sh
    - uses: actions/upload-artifact@v1
      with:
        name: ih8sn (AArch64)
        path: ih8sn-aarch64.zip
    - name: Build (ARMv7-A)
      run: |
        CXX=armv7a-linux-androideabi33-clang++ ./build.sh
        zip -r ih8sn-armv7a.zip META-INF system push.ps1 push.sh
    - uses: actions/upload-artifact@v1
      with:
        name: ih8sn (ARMv7-A)
        path: ih8sn-armv7a.zip
    - name: Build (i686)
      run: |
        CXX=i686-linux-android33-clang++ ./build.sh
        zip -r ih8sn-i686.zip META-INF system push.ps1 push.sh
    - uses: actions/upload-artifact@v1
      with:
        name: ih8sn (i686)
        path: ih8sn-i686.zip
    - name: Build (x86_64)
      run: |
        CXX=x86_64-linux-android33-clang++ ./build.sh
        zip -r ih8sn-x86_64.zip META-INF system push.ps1 push.sh
    - uses: actions/upload-artifact@v1
      with:
        name: ih8sn (x86_64)
        path: ih8sn-x86_64.zip
    - uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/flex'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-flex"
        prerelease: false
        title: "${{ env.GITHUB_SHA }}"
        files: |
          ih8sn-aarch64.zip
          ih8sn-armv7a.zip
          ih8sn-i686.zip
          ih8sn-x86_64.zip
